# Generated by Django 2.2.5 on 2020-01-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('bookName', models.TextField(null=True)),
            ],
        ),
    ]
